import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import static javax.swing.JOptionPane.showMessageDialog;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class RemoveFunction extends javax.swing.JFrame {
    String _id;
    DefaultTableModel _model;
    JTable _table = new javax.swing.JTable();
    ArrayList<Person> _list = new ArrayList<>();
    String _filelocation;
    
    public RemoveFunction(ArrayList<Person> list,DefaultTableModel model,JTable table,String filelocation) {
        _list = list;
        _filelocation = filelocation;
        _model = model;
        _table = table;
        initComponents();
         setTitle("gnome_child");
         ImageIcon icon;
         icon = new ImageIcon("src\\image\\icon.png");
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDLabel = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        TitleLabel = new javax.swing.JLabel();
        RemoveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(340, 310));
        setMinimumSize(new java.awt.Dimension(340, 310));
        setPreferredSize(new java.awt.Dimension(350, 340));
        setResizable(false);
        getContentPane().setLayout(null);

        IDLabel.setText("Enter the ID:");
        getContentPane().add(IDLabel);
        IDLabel.setBounds(10, 260, 80, 14);

        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });
        getContentPane().add(IDField);
        IDField.setBounds(80, 260, 80, 20);

        TitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitleLabel.setText("Remove Student");
        getContentPane().add(TitleLabel);
        TitleLabel.setBounds(0, 0, 139, 35);

        RemoveButton.setText("Remove");
        RemoveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveButtonMouseClicked(evt);
            }
        });
        getContentPane().add(RemoveButton);
        RemoveButton.setBounds(220, 260, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gnome_child.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 340, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveButtonMouseClicked
        _id = IDField.getText();
        boolean bool = false;
        for(int i = 0 ; i < _list.size(); i++){
            if(_list.get(i).getId().equals(_id)){
                showMessageDialog(null, _list.get(i).getFirstname() + " " + _list.get(i).getLastname() + " as been removed.");
                _model.removeRow( i );
                bool = true;
                _list.remove(i);
                UpdateFile();
                setVisible(false);
            }
        }
        if(bool = false){
            showMessageDialog(null,"This ID is not in the system");
        }
    }//GEN-LAST:event_RemoveButtonMouseClicked

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDFieldActionPerformed

    public void UpdateFile(){ //[WORKING]
        String content = "";
        for(int i = 0; i < (_list.size()); i++){// taking the information from the list and push it into the table
            String a = _list.get(i).getId();
            String b = _list.get(i).getFirstname();
            String c = _list.get(i).getLastname();
            String d = _list.get(i).getAge();
            String e = _list.get(i).getGender();
            String f = _list.get(i).getPhone();
            String g = _list.get(i).getProfession();
            String h = _list.get(i).getEmail();
            String i1 = _list.get(i).getYearsoflearning();
            content += a + " " + b +" " + c + " " + " " + d + " " + e + " " + f + " " + g + " " + h + " " + i1 +"\n";
        }
            writeUsingFiles(String.format("%s",content));
    }
        
        private void writeUsingFiles(String data) {
            try {
                Files.write(Paths.get(_filelocation), data.getBytes());
            }catch (IOException e) {
                  e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
